### PR TITLE
[spec/interpreter/test] Allow nullref type externally

### PR DESCRIPTION
**Pull request by rossberg**
Allow `nullref` in binary and text format as well as JS API.

Addresses #60.

### CODE REVIEW

**Comment by lars-t-hansen** [comment]
Overview must be updated too.

**Comment by lars-t-hansen** [comment]
I have no objections really to the change to ToWebAssemblyValue but it strikes me as not very JS-ish to throw an error if the incoming value is not null; more idiomatic might be to run ToPrimitive and then discard the result of that.  (It would be forward-compatible not to make this change now.)

**Comment by rossberg** [comment]
@lars-t-hansen, it is consistent with the existing rule for funcref, which doesn't try ToPrimitive either. Null isn't really treated as a value of primitive type in JS (its typeof is "object"), so using ToPrimitive would seem odd.

**Comment by lars-t-hansen** [comment]
Implementation just landed in SpiderMonkey.

**Comment by rossberg** [comment]
@lars-t-hansen, great to hear!

Is anything still blocking your approval to the PR?

**Comment by lars-t-hansen** [comment]
> Is anything still blocking your approval to the PR?

Not at all, PR is fine, I was just not asked for review earlier :-)

**Comment by rossberg** [comment]
Ah, sorry! Thanks for approving anyway!

**Pull request merged**
